# Generated by Django 3.2.9 on 2021-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rate',
            field=models.IntegerField(default=1500, verbose_name='rate'),
        ),
    ]
